# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=40)),
                ('longtitude', models.DecimalField(decimal_places=20, max_digits=40)),
                ('timestamp_last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
