# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0002_auto_20171002_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True),
        ),
    ]
