# Generated by Django 1.11.4 on 2017-10-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0003_auto_20171002_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
