# Generated by Django 1.11.4 on 2017-11-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0005_soda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soda',
            name='low_calorie',
            field=models.BooleanField(default=False),
        ),
    ]
