# Generated by Django 1.11.4 on 2017-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0006_auto_20171106_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='street_address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='soda',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='soda',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
