# Generated by Django 1.11.4 on 2017-11-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0007_auto_20171106_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soda',
            old_name='abbreviation',
            new_name='abb',
        ),
    ]
