# Generated by Django 1.11.4 on 2017-11-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0008_auto_20171106_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soda',
            old_name='abb',
            new_name='abbreviation',
        ),
    ]
