# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0009_auto_20171106_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='sodas',
            field=models.ManyToManyField(to='app1_findcokezero.Soda'),
        ),
    ]
