# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_findcokezero', '0011_auto_20171106_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailer',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
