"""
Django settings for findcoke1 project.

Generated by 'django-admin startproject' using Django 1.11.4.
Upgraded to Django 4.2.8 LTS.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: Do not run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ['true', '1', 'yes']

# SECURITY WARNING: Do not commit or share secret keys used in production.
# See README for information on managing secret keys.

GOOGLEMAPS_KEY = os.environ.get('GOOGLEMAPS_KEY', '')

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dev-key-only-for-local-development-do-not-use-in-production')

if os.environ.get('DATABASE_URL') and not os.environ.get('SECRET_KEY'):
    raise ValueError("SECRET_KEY must be set in production.")

ALLOWED_HOSTS = [
    'salty-crag-57705.herokuapp.com',
    'www.findcokezero.com',
    'localhost',
    '127.0.0.1' # standard loopback
]

# Application definition

INSTALLED_APPS = [
    'app1_findcokezero.apps.App1FindcokezeroConfig',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'findcoke1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'findcoke1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'findcoke_dev1',
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': '',
        'HOST': 'localhost',    # 'localhost' explicitly uses TCP/IP; empty string defaults to Unix domain socket
        'PORT': '',             # empty string defaults to PostgreSQL's standard port 5432
    }
}

# If DATABASE_URL environment variable is detected, its value will overwrite default configuration above.
# NB: Heroku (production environment) automatically sets DATABASE_URL.
if os.environ.get('DATABASE_URL'):
    DATABASES['default'].update(dj_database_url.config(conn_max_age=500))

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# builds a path inside the file structure
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


# Static files (CSS, JavaScript, Images) need to be found and loaded
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

# Here: list all the places you want the system to look for loading static files when 'collectstatic' command is run.
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'static'),
)

# Simplified static file serving. Added this because Django does not automatically support serving static files in production.
# https://warehouse.python.org/project/whitenoise/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Detect Heroku environment (historicaly used for production)
ON_HEROKU = os.environ.get('DYNO') is not None

# HTTPS/SSL Configuration for Heroku, which automates provision of SSL certificates
if ON_HEROKU:
    # redirect all HTTP requests to HTTPS
    SECURE_SSL_REDIRECT = True

    # tell Django to trust the X-Forwarded-Proto header from Heroku's load balancer
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')