# Generated by Django 4.2.18 on 2025-12-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
                ('low_calorie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=40, null=True)),
                ('timestamp_last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('sodas', models.ManyToManyField(blank=True, to='inventory.soda')),
            ],
        ),
    ]
